directive @isAuthenticated on FIELD | FIELD_DEFINITION
#/* -------------------------------------------------------------------------- */
#/*                                GraphQL Types                               */
#/* -------------------------------------------------------------------------- */

type User {
    id: ID!
    name: String
    email: String
    message: String
    createdAt: String
    updatedAt: String
}
type ShortLink {
    id: ID
    original_url: String
    short_url: String
    createdAt: DateTime
    updatedAt: DateTime
    title: String
    clicks: Int
}

#/* -------------------------------------------------------------------------- */
#/*                               GraphQL Queries                              */
#/* -------------------------------------------------------------------------- */

type Query {
    users: [User] @isAuthenticated
    user(id: String): User @isAuthenticated
    shortLinks: [ShortLink]
}

#/* -------------------------------------------------------------------------- */
#/*                              GraphQL Mutations                             */
#/* -------------------------------------------------------------------------- */

type Mutation {
    signUp(name: String!, email: String!, password: String!): User
    signIn(email: String!, password: String!): JSONObject
    createShortLink(
        original_url: String!
        title: String!
        short_url: String
    ): ShortLink
}

#/* -------------------------------------------------------------------------- */
#/*                            GraphQL Subscriptions                           */
#/* -------------------------------------------------------------------------- */

type Subscription {
    welcomeMessage: String
}
