directive @isAuthenticated on FIELD | FIELD_DEFINITION
#/* -------------------------------------------------------------------------- */
#/*                                GraphQL Types                               */
#/* -------------------------------------------------------------------------- */

type User {
    id: ID!
    name: String
    email: String
    message: String
    createdAt: String
    updatedAt: String
}
type ShortLink {
    id: ID
    original_url: String
    short_url: String
    createdAt: DateTime
    updatedAt: DateTime
    title: String
    clicks: Int
    user_id: String
}

#/* -------------------------------------------------------------------------- */
#/*                               GraphQL Queries                              */
#/* -------------------------------------------------------------------------- */

type Query {
    users: [User] @isAuthenticated
    auth_user: User @isAuthenticated
    short_links: [ShortLink] @isAuthenticated
}

#/* -------------------------------------------------------------------------- */
#/*                              GraphQL Mutations                             */
#/* -------------------------------------------------------------------------- */

type Mutation {
    signup(name: String!, email: EmailAddress!, password: String!): User
    signin(email: EmailAddress!, password: String!): JSONObject
    create_shortLink(
        original_url: String!
        title: String!
        short_url: String
    ): ShortLink
    update_link_info(
        id: String!
        original_url: String!
        title: String!
        short_url: String!
    ): ShortLink
    remove_all_users(key: String!): Boolean
    remove_all_links(key: String!): Boolean
    remove_link(id: String!): Boolean
}

#/* -------------------------------------------------------------------------- */
#/*                            GraphQL Subscriptions                           */
#/* -------------------------------------------------------------------------- */

type Subscription {
    welcomeMessage: String
}
